package api

func getPokemonName(pokemonId float64, formIndex float64) string {
	switch pokemonId {
	case 1:
		return "Bulbasaur"
	case 2:
		return "Ivysaur"
	case 3:
		switch formIndex {
		case 0:
			return "Venusaur"
		case 1:
			return "Venusaur-mega"
		case 2:
			return "Venusaur-gigantamax"
		}
		return "Venusaur"
	case 4:
		return "Charmander"
	case 5:
		return "Charmeleon"
	case 6:
		switch formIndex {
		case 0:
			return "Charizard"
		case 1:
			return "Charizard-mega-x"
		case 2:
			return "Charizard-mega-y"
		case 3:
			return "Charizard-gigantamax"
		}
		return "Charizard"
	case 7:
		return "Squirtle"
	case 8:
		return "Wartortle"
	case 9:
		switch formIndex {
		case 0:
			return "Blastoise"
		case 1:
			return "Blastoise-mega"
		case 2:
			return "Blastoise-gigantamax"
		}
		return "Blastoise"
	case 10:
		return "Caterpie"
	case 11:
		return "Metapod"
	case 12:
		switch formIndex {
		case 0:
			return "Butterfree"
		case 1:
			return "Butterfree-gigantamax"
		}
		return "Butterfree"
	case 13:
		return "Weedle"
	case 14:
		return "Kakuna"
	case 15:
		switch formIndex {
		case 0:
			return "Beedrill"
		case 1:
			return "Beedrill-mega"
		}
		return "Beedrill"
	case 16:
		return "Pidgey"
	case 17:
		return "Pidgeotto"
	case 18:
		switch formIndex {
		case 0:
			return "Pidgeot"
		case 1:
			return "Pidgeot-mega"
		}
		return "Pidgeot"
	case 19:
		return "Rattata"
	case 20:
		return "Raticate"
	case 21:
		return "Spearow"
	case 22:
		return "Fearow"
	case 23:
		return "Ekans"
	case 24:
		return "Arbok"
	case 25:
		switch formIndex {
		case 0:
			return "Pikachu"
		case 1:
			return "Pikachu-partner"
		case 2:
			return "Pikachu-cosplay"
		case 3:
			return "Pikachu-cool-cosplay"
		case 4:
			return "Pikachu-beauty-cosplay"
		case 5:
			return "Pikachu-cute-cosplay"
		case 6:
			return "Pikachu-smart-cosplay"
		case 7:
			return "Pikachu-tough-cosplay"
		case 8:
			return "Pikachu-gigantamax"
		}
		return "Pikachu"
	case 26:
		return "Raichu"
	case 27:
		return "Sandshrew"
	case 28:
		return "Sandslash"
	case 29:
		return "Nidoran♀"
	case 30:
		return "Nidorina"
	case 31:
		return "Nidoqueen"
	case 32:
		return "Nidoran♂"
	case 33:
		return "Nidorino"
	case 34:
		return "Nidoking"
	case 35:
		return "Clefairy"
	case 36:
		return "Clefable"
	case 37:
		return "Vulpix"
	case 38:
		return "Ninetales"
	case 39:
		return "Jigglypuff"
	case 40:
		return "Wigglytuff"
	case 41:
		return "Zubat"
	case 42:
		return "Golbat"
	case 43:
		return "Oddish"
	case 44:
		return "Gloom"
	case 45:
		return "Vileplume"
	case 46:
		return "Paras"
	case 47:
		return "Parasect"
	case 48:
		return "Venonat"
	case 49:
		return "Venomoth"
	case 50:
		return "Diglett"
	case 51:
		return "Dugtrio"
	case 52:
		switch formIndex {
		case 0:
			return "Meowth"
		case 1:
			return "Meowth-gigantamax"
		}
		return "Meowth"
	case 53:
		return "Persian"
	case 54:
		return "Psyduck"
	case 55:
		return "Golduck"
	case 56:
		return "Mankey"
	case 57:
		return "Primeape"
	case 58:
		return "Growlithe"
	case 59:
		return "Arcanine"
	case 60:
		return "Poliwag"
	case 61:
		return "Poliwhirl"
	case 62:
		return "Poliwrath"
	case 63:
		return "Abra"
	case 64:
		return "Kadabra"
	case 65:
		switch formIndex {
		case 0:
			return "Alakazam"
		case 1:
			return "Alakazam-mega"
		}
		return "Alakazam"
	case 66:
		return "Machop"
	case 67:
		return "Machoke"
	case 68:
		switch formIndex {
		case 0:
			return "Machamp"
		case 1:
			return "Machamp-gigantamax"
		}
		return "Machamp"
	case 69:
		return "Bellsprout"
	case 70:
		return "Weepinbell"
	case 71:
		return "Victreebel"
	case 72:
		return "Tentacool"
	case 73:
		return "Tentacruel"
	case 74:
		return "Geodude"
	case 75:
		return "Graveler"
	case 76:
		return "Golem"
	case 77:
		return "Ponyta"
	case 78:
		return "Rapidash"
	case 79:
		return "Slowpoke"
	case 80:
		switch formIndex {
		case 0:
			return "Slowbro"
		case 1:
			return "Slowbro-mega"
		}
		return "Slowbro"
	case 81:
		return "Magnemite"
	case 82:
		return "Magneton"
	case 83:
		return "Farfetch'd"
	case 84:
		return "Doduo"
	case 85:
		return "Dodrio"
	case 86:
		return "Seel"
	case 87:
		return "Dewgong"
	case 88:
		return "Grimer"
	case 89:
		return "Muk"
	case 90:
		return "Shellder"
	case 91:
		return "Cloyster"
	case 92:
		return "Gastly"
	case 93:
		return "Haunter"
	case 94:
		switch formIndex {
		case 0:
			return "Gengar"
		case 1:
			return "Gengar-mega"
		case 2:
			return "Gengar-gigantamax"
		}
		return "Gengar"
	case 95:
		return "Onix"
	case 96:
		return "Drowzee"
	case 97:
		return "Hypno"
	case 98:
		return "Krabby"
	case 99:
		switch formIndex {
		case 0:
			return "Kingler"
		case 1:
			return "Kingler-gigantamax"
		}
		return "Kingler"
	case 100:
		return "Voltorb"
	case 101:
		return "Electrode"
	case 102:
		return "Exeggcute"
	case 103:
		return "Exeggutor"
	case 104:
		return "Cubone"
	case 105:
		return "Marowak"
	case 106:
		return "Hitmonlee"
	case 107:
		return "Hitmonchan"
	case 108:
		return "Lickitung"
	case 109:
		return "Koffing"
	case 110:
		return "Weezing"
	case 111:
		return "Rhyhorn"
	case 112:
		return "Rhydon"
	case 113:
		return "Chansey"
	case 114:
		return "Tangela"
	case 115:
		switch formIndex {
		case 0:
			return "Kangaskhan"
		case 1:
			return "Kangaskhan-mega"
		}
		return "Kangaskhan"
	case 116:
		return "Horsea"
	case 117:
		return "Seadra"
	case 118:
		return "Goldeen"
	case 119:
		return "Seaking"
	case 120:
		return "Staryu"
	case 121:
		return "Starmie"
	case 122:
		return "Mr. Mime"
	case 123:
		return "Scyther"
	case 124:
		return "Jynx"
	case 125:
		return "Electabuzz"
	case 126:
		return "Magmar"
	case 127:
		switch formIndex {
		case 0:
			return "Pinsir"
		case 1:
			return "Pinsir-mega"
		}
		return "Pinsir"
	case 128:
		return "Tauros"
	case 129:
		return "Magikarp"
	case 130:
		switch formIndex {
		case 0:
			return "Gyarados"
		case 1:
			return "Gyarados-mega"
		}
		return "Gyarados"
	case 131:
		switch formIndex {
		case 0:
			return "Lapras"
		case 1:
			return "Lapras-gigantamax"
		}
		return "Lapras"
	case 132:
		return "Ditto"
	case 133:
		switch formIndex {
		case 0:
			return "Eevee"
		case 1:
			return "Eevee-partner"
		case 2:
			return "Eevee-gigantamax"
		}
		return "Eevee"
	case 134:
		return "Vaporeon"
	case 135:
		return "Jolteon"
	case 136:
		return "Flareon"
	case 137:
		return "Porygon"
	case 138:
		return "Omanyte"
	case 139:
		return "Omastar"
	case 140:
		return "Kabuto"
	case 141:
		return "Kabutops"
	case 142:
		switch formIndex {
		case 0:
			return "Aerodactyl"
		case 1:
			return "Aerodactyl-mega"
		}
		return "Aerodactyl"
	case 143:
		switch formIndex {
		case 0:
			return "Snorlax"
		case 1:
			return "Snorlax-gigantamax"
		}
		return "Snorlax"
	case 144:
		return "Articuno"
	case 145:
		return "Zapdos"
	case 146:
		return "Moltres"
	case 147:
		return "Dratini"
	case 148:
		return "Dragonair"
	case 149:
		return "Dragonite"
	case 150:
		switch formIndex {
		case 0:
			return "Mewtwo"
		case 1:
			return "Mewtwo-mega-x"
		case 2:
			return "Mewtwo-mega-y"
		}
		return "Mewtwo"
	case 151:
		return "Mew"
	case 152:
		return "Chikorita"
	case 153:
		return "Bayleef"
	case 154:
		return "Meganium"
	case 155:
		return "Cyndaquil"
	case 156:
		return "Quilava"
	case 157:
		return "Typhlosion"
	case 158:
		return "Totodile"
	case 159:
		return "Croconaw"
	case 160:
		return "Feraligatr"
	case 161:
		return "Sentret"
	case 162:
		return "Furret"
	case 163:
		return "Hoothoot"
	case 164:
		return "Noctowl"
	case 165:
		return "Ledyba"
	case 166:
		return "Ledian"
	case 167:
		return "Spinarak"
	case 168:
		return "Ariados"
	case 169:
		return "Crobat"
	case 170:
		return "Chinchou"
	case 171:
		return "Lanturn"
	case 172:
		switch formIndex {
		case 0:
			return "Pichu"
		case 1:
			return "Pichu-spiky"
		}
		return "Pichu"
	case 173:
		return "Cleffa"
	case 174:
		return "Igglybuff"
	case 175:
		return "Togepi"
	case 176:
		return "Togetic"
	case 177:
		return "Natu"
	case 178:
		return "Xatu"
	case 179:
		return "Mareep"
	case 180:
		return "Flaaffy"
	case 181:
		switch formIndex {
		case 0:
			return "Ampharos"
		case 1:
			return "Ampharos-mega"
		}
		return "Ampharos"
	case 182:
		return "Bellossom"
	case 183:
		return "Marill"
	case 184:
		return "Azumarill"
	case 185:
		return "Sudowoodo"
	case 186:
		return "Politoed"
	case 187:
		return "Hoppip"
	case 188:
		return "Skiploom"
	case 189:
		return "Jumpluff"
	case 190:
		return "Aipom"
	case 191:
		return "Sunkern"
	case 192:
		return "Sunflora"
	case 193:
		return "Yanma"
	case 194:
		return "Wooper"
	case 195:
		return "Quagsire"
	case 196:
		return "Espeon"
	case 197:
		return "Umbreon"
	case 198:
		return "Murkrow"
	case 199:
		return "Slowking"
	case 200:
		return "Misdreavus"
	case 201:
		switch formIndex {
		case 0:
			return "Unown-a"
		case 1:
			return "Unown-b"
		case 2:
			return "Unown-c"
		case 3:
			return "Unown-d"
		case 4:
			return "Unown-e"
		case 5:
			return "Unown-f"
		case 6:
			return "Unown-g"
		case 7:
			return "Unown-h"
		case 8:
			return "Unown-i"
		case 9:
			return "Unown-j"
		case 10:
			return "Unown-k"
		case 11:
			return "Unown-l"
		case 12:
			return "Unown-m"
		case 13:
			return "Unown-n"
		case 14:
			return "Unown-o"
		case 15:
			return "Unown-p"
		case 16:
			return "Unown-q"
		case 17:
			return "Unown-r"
		case 18:
			return "Unown-s"
		case 19:
			return "Unown-t"
		case 20:
			return "Unown-u"
		case 21:
			return "Unown-v"
		case 22:
			return "Unown-w"
		case 23:
			return "Unown-x"
		case 24:
			return "Unown-y"
		case 25:
			return "Unown-z"
		case 26:
			return "Unown-exclamation"
		case 27:
			return "Unown-question"
		}
		return "Unown"
	case 202:
		return "Wobbuffet"
	case 203:
		return "Girafarig"
	case 204:
		return "Pineco"
	case 205:
		return "Forretress"
	case 206:
		return "Dunsparce"
	case 207:
		return "Gligar"
	case 208:
		switch formIndex {
		case 0:
			return "Steelix"
		case 1:
			return "Steelix-mega"
		}
		return "Steelix"
	case 209:
		return "Snubbull"
	case 210:
		return "Granbull"
	case 211:
		return "Qwilfish"
	case 212:
		switch formIndex {
		case 0:
			return "Scizor"
		case 1:
			return "Scizor-mega"
		}
		return "Scizor"
	case 213:
		return "Shuckle"
	case 214:
		switch formIndex {
		case 0:
			return "Heracross"
		case 1:
			return "Heracross-mega"
		}
		return "Heracross"
	case 215:
		return "Sneasel"
	case 216:
		return "Teddiursa"
	case 217:
		return "Ursaring"
	case 218:
		return "Slugma"
	case 219:
		return "Magcargo"
	case 220:
		return "Swinub"
	case 221:
		return "Piloswine"
	case 222:
		return "Corsola"
	case 223:
		return "Remoraid"
	case 224:
		return "Octillery"
	case 225:
		return "Delibird"
	case 226:
		return "Mantine"
	case 227:
		return "Skarmory"
	case 228:
		return "Houndour"
	case 229:
		switch formIndex {
		case 0:
			return "Houndoom"
		case 1:
			return "Houndoom-mega"
		}
		return "Houndoom"
	case 230:
		return "Kingdra"
	case 231:
		return "Phanpy"
	case 232:
		return "Donphan"
	case 233:
		return "Porygon2"
	case 234:
		return "Stantler"
	case 235:
		return "Smeargle"
	case 236:
		return "Tyrogue"
	case 237:
		return "Hitmontop"
	case 238:
		return "Smoochum"
	case 239:
		return "Elekid"
	case 240:
		return "Magby"
	case 241:
		return "Miltank"
	case 242:
		return "Blissey"
	case 243:
		return "Raikou"
	case 244:
		return "Entei"
	case 245:
		return "Suicune"
	case 246:
		return "Larvitar"
	case 247:
		return "Pupitar"
	case 248:
		switch formIndex {
		case 0:
			return "Tyranitar"
		case 1:
			return "Tyranitar-mega"
		}
		return "Tyranitar"
	case 249:
		return "Lugia"
	case 250:
		return "Ho-Oh"
	case 251:
		return "Celebi"
	case 252:
		return "Treecko"
	case 253:
		return "Grovyle"
	case 254:
		switch formIndex {
		case 0:
			return "Sceptile"
		case 1:
			return "Sceptile-mega"
		}
		return "Sceptile"
	case 255:
		return "Torchic"
	case 256:
		return "Combusken"
	case 257:
		switch formIndex {
		case 0:
			return "Blaziken"
		case 1:
			return "Blaziken-mega"
		}
		return "Blaziken"
	case 258:
		return "Mudkip"
	case 259:
		return "Marshtomp"
	case 260:
		switch formIndex {
		case 0:
			return "Swampert"
		case 1:
			return "Swampert-mega"
		}
		return "Swampert"
	case 261:
		return "Poochyena"
	case 262:
		return "Mightyena"
	case 263:
		return "Zigzagoon"
	case 264:
		return "Linoone"
	case 265:
		return "Wurmple"
	case 266:
		return "Silcoon"
	case 267:
		return "Beautifly"
	case 268:
		return "Cascoon"
	case 269:
		return "Dustox"
	case 270:
		return "Lotad"
	case 271:
		return "Lombre"
	case 272:
		return "Ludicolo"
	case 273:
		return "Seedot"
	case 274:
		return "Nuzleaf"
	case 275:
		return "Shiftry"
	case 276:
		return "Taillow"
	case 277:
		return "Swellow"
	case 278:
		return "Wingull"
	case 279:
		return "Pelipper"
	case 280:
		return "Ralts"
	case 281:
		return "Kirlia"
	case 282:
		switch formIndex {
		case 0:
			return "Gardevoir"
		case 1:
			return "Gardevoir-mega"
		}
		return "Gardevoir"
	case 283:
		return "Surskit"
	case 284:
		return "Masquerain"
	case 285:
		return "Shroomish"
	case 286:
		return "Breloom"
	case 287:
		return "Slakoth"
	case 288:
		return "Vigoroth"
	case 289:
		return "Slaking"
	case 290:
		return "Nincada"
	case 291:
		return "Ninjask"
	case 292:
		return "Shedinja"
	case 293:
		return "Whismur"
	case 294:
		return "Loudred"
	case 295:
		return "Exploud"
	case 296:
		return "Makuhita"
	case 297:
		return "Hariyama"
	case 298:
		return "Azurill"
	case 299:
		return "Nosepass"
	case 300:
		return "Skitty"
	case 301:
		return "Delcatty"
	case 302:
		switch formIndex {
		case 0:
			return "Sableye"
		case 1:
			return "Sableye-mega"
		}
		return "Sableye"
	case 303:
		switch formIndex {
		case 0:
			return "Mawile"
		case 1:
			return "Mawile-mega"
		}
		return "Mawile"
	case 304:
		return "Aron"
	case 305:
		return "Lairon"
	case 306:
		switch formIndex {
		case 0:
			return "Aggron"
		case 1:
			return "Aggron-mega"
		}
		return "Aggron"
	case 307:
		return "Meditite"
	case 308:
		switch formIndex {
		case 0:
			return "Medicham"
		case 1:
			return "Medicham-mega"
		}
		return "Medicham"
	case 309:
		return "Electrike"
	case 310:
		switch formIndex {
		case 0:
			return "Manectric"
		case 1:
			return "Manectric-mega"
		}
		return "Manectric"
	case 311:
		return "Plusle"
	case 312:
		return "Minun"
	case 313:
		return "Volbeat"
	case 314:
		return "Illumise"
	case 315:
		return "Roselia"
	case 316:
		return "Gulpin"
	case 317:
		return "Swalot"
	case 318:
		return "Carvanha"
	case 319:
		switch formIndex {
		case 0:
			return "Sharpedo"
		case 1:
			return "Sharpedo-mega"
		}
		return "Sharpedo"
	case 320:
		return "Wailmer"
	case 321:
		return "Wailord"
	case 322:
		return "Numel"
	case 323:
		switch formIndex {
		case 0:
			return "Camerupt"
		case 1:
			return "Camerupt-mega"
		}
		return "Camerupt"
	case 324:
		return "Torkoal"
	case 325:
		return "Spoink"
	case 326:
		return "Grumpig"
	case 327:
		return "Spinda"
	case 328:
		return "Trapinch"
	case 329:
		return "Vibrava"
	case 330:
		return "Flygon"
	case 331:
		return "Cacnea"
	case 332:
		return "Cacturne"
	case 333:
		return "Swablu"
	case 334:
		switch formIndex {
		case 0:
			return "Altaria"
		case 1:
			return "Altaria-mega"
		}
		return "Altaria"
	case 335:
		return "Zangoose"
	case 336:
		return "Seviper"
	case 337:
		return "Lunatone"
	case 338:
		return "Solrock"
	case 339:
		return "Barboach"
	case 340:
		return "Whiscash"
	case 341:
		return "Corphish"
	case 342:
		return "Crawdaunt"
	case 343:
		return "Baltoy"
	case 344:
		return "Claydol"
	case 345:
		return "Lileep"
	case 346:
		return "Cradily"
	case 347:
		return "Anorith"
	case 348:
		return "Armaldo"
	case 349:
		return "Feebas"
	case 350:
		return "Milotic"
	case 351:
		switch formIndex {
		case 0:
			return "Castform"
		case 1:
			return "Castform-sunny"
		case 2:
			return "Castform-rainy"
		case 3:
			return "Castform-snowy"
		}
		return "Castform"
	case 352:
		return "Kecleon"
	case 353:
		return "Shuppet"
	case 354:
		switch formIndex {
		case 0:
			return "Banette"
		case 1:
			return "Banette-mega"
		}
		return "Banette"
	case 355:
		return "Duskull"
	case 356:
		return "Dusclops"
	case 357:
		return "Tropius"
	case 358:
		return "Chimecho"
	case 359:
		switch formIndex {
		case 0:
			return "Absol"
		case 1:
			return "Absol-mega"
		}
		return "Absol"
	case 360:
		return "Wynaut"
	case 361:
		return "Snorunt"
	case 362:
		switch formIndex {
		case 0:
			return "Glalie"
		case 1:
			return "Glalie-mega"
		}
		return "Glalie"
	case 363:
		return "Spheal"
	case 364:
		return "Sealeo"
	case 365:
		return "Walrein"
	case 366:
		return "Clamperl"
	case 367:
		return "Huntail"
	case 368:
		return "Gorebyss"
	case 369:
		return "Relicanth"
	case 370:
		return "Luvdisc"
	case 371:
		return "Bagon"
	case 372:
		return "Shelgon"
	case 373:
		switch formIndex {
		case 0:
			return "Salamence"
		case 1:
			return "Salamence-mega"
		}
		return "Salamence"
	case 374:
		return "Beldum"
	case 375:
		return "Metang"
	case 376:
		switch formIndex {
		case 0:
			return "Metagross"
		case 1:
			return "Metagross-mega"
		}
		return "Metagross"
	case 377:
		return "Regirock"
	case 378:
		return "Regice"
	case 379:
		return "Registeel"
	case 380:
		switch formIndex {
		case 0:
			return "Latias"
		case 1:
			return "Latias-mega"
		}
		return "Latias"
	case 381:
		switch formIndex {
		case 0:
			return "Latios"
		case 1:
			return "Latios-mega"
		}
		return "Latios"
	case 382:
		switch formIndex {
		case 0:
			return "Kyogre"
		case 1:
			return "Kyogre-primal"
		}
		return "Kyogre"
	case 383:
		switch formIndex {
		case 0:
			return "Groudon"
		case 1:
			return "Groudon-primal"
		}
		return "Groudon"
	case 384:
		switch formIndex {
		case 0:
			return "Rayquaza"
		case 1:
			return "Rayquaza-mega"
		}
		return "Rayquaza"
	case 385:
		return "Jirachi"
	case 386:
		switch formIndex {
		case 0:
			return "Deoxys"
		case 1:
			return "Deoxys-attack"
		case 2:
			return "Deoxys-defense"
		case 3:
			return "Deoxys-speed"
		}
		return "Deoxys"
	case 387:
		return "Turtwig"
	case 388:
		return "Grotle"
	case 389:
		return "Torterra"
	case 390:
		return "Chimchar"
	case 391:
		return "Monferno"
	case 392:
		return "Infernape"
	case 393:
		return "Piplup"
	case 394:
		return "Prinplup"
	case 395:
		return "Empoleon"
	case 396:
		return "Starly"
	case 397:
		return "Staravia"
	case 398:
		return "Staraptor"
	case 399:
		return "Bidoof"
	case 400:
		return "Bibarel"
	case 401:
		return "Kricketot"
	case 402:
		return "Kricketune"
	case 403:
		return "Shinx"
	case 404:
		return "Luxio"
	case 405:
		return "Luxray"
	case 406:
		return "Budew"
	case 407:
		return "Roserade"
	case 408:
		return "Cranidos"
	case 409:
		return "Rampardos"
	case 410:
		return "Shieldon"
	case 411:
		return "Bastiodon"
	case 412:
		switch formIndex {
		case 0:
			return "Burmy-plant"
		case 1:
			return "Burmy-sandy"
		case 2:
			return "Burmy-trash"
		}
		return "Burmy"
	case 413:
		switch formIndex {
		case 0:
			return "Wormadam-plant"
		case 1:
			return "Wormadam-sandy"
		case 2:
			return "Wormadam-trash"
		}
		return "Wormadam"
	case 414:
		return "Mothim"
	case 415:
		return "Combee"
	case 416:
		return "Vespiquen"
	case 417:
		return "Pachirisu"
	case 418:
		return "Buizel"
	case 419:
		return "Floatzel"
	case 420:
		return "Cherubi"
	case 421:
		switch formIndex {
		case 0:
			return "Cherrim-overcast"
		case 1:
			return "Cherrim-sunshine"
		}
		return "Cherrim"
	case 422:
		switch formIndex {
		case 0:
			return "Shellos-east"
		case 1:
			return "Shellos-west"
		}
		return "Shellos"
	case 423:
		switch formIndex {
		case 0:
			return "Gastrodon-east"
		case 1:
			return "Gastrodon-west"
		}
		return "Gastrodon"
	case 424:
		return "Ambipom"
	case 425:
		return "Drifloon"
	case 426:
		return "Drifblim"
	case 427:
		return "Buneary"
	case 428:
		switch formIndex {
		case 0:
			return "Lopunny"
		case 1:
			return "Lopunny-mega"
		}
		return "Lopunny"
	case 429:
		return "Mismagius"
	case 430:
		return "Honchkrow"
	case 431:
		return "Glameow"
	case 432:
		return "Purugly"
	case 433:
		return "Chingling"
	case 434:
		return "Stunky"
	case 435:
		return "Skuntank"
	case 436:
		return "Bronzor"
	case 437:
		return "Bronzong"
	case 438:
		return "Bonsly"
	case 439:
		return "Mime Jr."
	case 440:
		return "Happiny"
	case 441:
		return "Chatot"
	case 442:
		return "Spiritomb"
	case 443:
		return "Gible"
	case 444:
		return "Gabite"
	case 445:
		switch formIndex {
		case 0:
			return "Garchomp"
		case 1:
			return "Garchomp-mega"
		}
		return "Garchomp"
	case 446:
		return "Munchlax"
	case 447:
		return "Riolu"
	case 448:
		switch formIndex {
		case 0:
			return "Lucario"
		case 1:
			return "Lucario-mega"
		}
		return "Lucario"
	case 449:
		return "Hippopotas"
	case 450:
		return "Hippowdon"
	case 451:
		return "Skorupi"
	case 452:
		return "Drapion"
	case 453:
		return "Croagunk"
	case 454:
		return "Toxicroak"
	case 455:
		return "Carnivine"
	case 456:
		return "Finneon"
	case 457:
		return "Lumineon"
	case 458:
		return "Mantyke"
	case 459:
		return "Snover"
	case 460:
		switch formIndex {
		case 0:
			return "Abomasnow"
		case 1:
			return "Abomasnow-mega"
		}
		return "Abomasnow"
	case 461:
		return "Weavile"
	case 462:
		return "Magnezone"
	case 463:
		return "Lickilicky"
	case 464:
		return "Rhyperior"
	case 465:
		return "Tangrowth"
	case 466:
		return "Electivire"
	case 467:
		return "Magmortar"
	case 468:
		return "Togekiss"
	case 469:
		return "Yanmega"
	case 470:
		return "Leafeon"
	case 471:
		return "Glaceon"
	case 472:
		return "Gliscor"
	case 473:
		return "Mamoswine"
	case 474:
		return "Porygon-Z"
	case 475:
		switch formIndex {
		case 0:
			return "Gallade"
		case 1:
			return "Gallade-mega"
		}
		return "Gallade"
	case 476:
		return "Probopass"
	case 477:
		return "Dusknoir"
	case 478:
		return "Froslass"
	case 479:
		switch formIndex {
		case 0:
			return "Rotom"
		case 1:
			return "Rotom-heat"
		case 2:
			return "Rotom-wash"
		case 3:
			return "Rotom-frost"
		case 4:
			return "Rotom-fan"
		case 5:
			return "Rotom-mow"
		}
		return "Rotom"
	case 480:
		return "Uxie"
	case 481:
		return "Mesprit"
	case 482:
		return "Azelf"
	case 483:
		switch formIndex {
		case 0:
			return "Dialga"
		case 1:
			return "Dialga-origin"
		}
		return "Dialga"
	case 484:
		switch formIndex {
		case 0:
			return "Palkia"
		case 1:
			return "Palkia-origin"
		}
		return "Palkia"
	case 485:
		return "Heatran"
	case 486:
		return "Regigigas"
	case 487:
		switch formIndex {
		case 0:
			return "Giratina-altered"
		case 1:
			return "Giratina-origin"
		}
		return "Giratina"
	case 488:
		return "Cresselia"
	case 489:
		return "Phione"
	case 490:
		return "Manaphy"
	case 491:
		return "Darkrai"
	case 492:
		switch formIndex {
		case 0:
			return "Shaymin-land"
		case 1:
			return "Shaymin-sky"
		}
		return "Shaymin"
	case 493:
		switch formIndex {
		case 0:
			return "Arceus-normal"
		case 1:
			return "Arceus-fighting"
		case 2:
			return "Arceus-flying"
		case 3:
			return "Arceus-poison"
		case 4:
			return "Arceus-ground"
		case 5:
			return "Arceus-rock"
		case 6:
			return "Arceus-bug"
		case 7:
			return "Arceus-ghost"
		case 8:
			return "Arceus-steel"
		case 9:
			return "Arceus-fire"
		case 10:
			return "Arceus-water"
		case 11:
			return "Arceus-grass"
		case 12:
			return "Arceus-electric"
		case 13:
			return "Arceus-psychic"
		case 14:
			return "Arceus-ice"
		case 15:
			return "Arceus-dragon"
		case 16:
			return "Arceus-dark"
		case 17:
			return "Arceus-fairy"
		case 18:
			return "Arceus-unknown"
		}
		return "Arceus"
	case 494:
		return "Victini"
	case 495:
		return "Snivy"
	case 496:
		return "Servine"
	case 497:
		return "Serperior"
	case 498:
		return "Tepig"
	case 499:
		return "Pignite"
	case 500:
		return "Emboar"
	case 501:
		return "Oshawott"
	case 502:
		return "Dewott"
	case 503:
		return "Samurott"
	case 504:
		return "Patrat"
	case 505:
		return "Watchog"
	case 506:
		return "Lillipup"
	case 507:
		return "Herdier"
	case 508:
		return "Stoutland"
	case 509:
		return "Purrloin"
	case 510:
		return "Liepard"
	case 511:
		return "Pansage"
	case 512:
		return "Simisage"
	case 513:
		return "Pansear"
	case 514:
		return "Simisear"
	case 515:
		return "Panpour"
	case 516:
		return "Simipour"
	case 517:
		return "Munna"
	case 518:
		return "Musharna"
	case 519:
		return "Pidove"
	case 520:
		return "Tranquill"
	case 521:
		return "Unfezant"
	case 522:
		return "Blitzle"
	case 523:
		return "Zebstrika"
	case 524:
		return "Roggenrola"
	case 525:
		return "Boldore"
	case 526:
		return "Gigalith"
	case 527:
		return "Woobat"
	case 528:
		return "Swoobat"
	case 529:
		return "Drilbur"
	case 530:
		return "Excadrill"
	case 531:
		switch formIndex {
		case 0:
			return "Audino"
		case 1:
			return "Audino-mega"
		}
		return "Audino"
	case 532:
		return "Timburr"
	case 533:
		return "Gurdurr"
	case 534:
		return "Conkeldurr"
	case 535:
		return "Tympole"
	case 536:
		return "Palpitoad"
	case 537:
		return "Seismitoad"
	case 538:
		return "Throh"
	case 539:
		return "Sawk"
	case 540:
		return "Sewaddle"
	case 541:
		return "Swadloon"
	case 542:
		return "Leavanny"
	case 543:
		return "Venipede"
	case 544:
		return "Whirlipede"
	case 545:
		return "Scolipede"
	case 546:
		return "Cottonee"
	case 547:
		return "Whimsicott"
	case 548:
		return "Petilil"
	case 549:
		return "Lilligant"
	case 550:
		switch formIndex {
		case 0:
			return "Basculin-red-striped"
		case 1:
			return "Basculin-blue-striped"
		case 2:
			return "Basculin-white-striped"
		}
		return "Basculin"
	case 551:
		return "Sandile"
	case 552:
		return "Krokorok"
	case 553:
		return "Krookodile"
	case 554:
		return "Darumaka"
	case 555:
		switch formIndex {
		case 0:
			return "Darmanitan"
		case 1:
			return "Darmanitan-zen"
		}
		return "Darmanitan"
	case 556:
		return "Maractus"
	case 557:
		return "Dwebble"
	case 558:
		return "Crustle"
	case 559:
		return "Scraggy"
	case 560:
		return "Scrafty"
	case 561:
		return "Sigilyph"
	case 562:
		return "Yamask"
	case 563:
		return "Cofagrigus"
	case 564:
		return "Tirtouga"
	case 565:
		return "Carracosta"
	case 566:
		return "Archen"
	case 567:
		return "Archeops"
	case 568:
		return "Trubbish"
	case 569:
		switch formIndex {
		case 0:
			return "Garbodor"
		case 1:
			return "Garbodor-gigantamax"
		}
		return "Garbodor"
	case 570:
		return "Zorua"
	case 571:
		return "Zoroark"
	case 572:
		return "Minccino"
	case 573:
		return "Cinccino"
	case 574:
		return "Gothita"
	case 575:
		return "Gothorita"
	case 576:
		return "Gothitelle"
	case 577:
		return "Solosis"
	case 578:
		return "Duosion"
	case 579:
		return "Reuniclus"
	case 580:
		return "Ducklett"
	case 581:
		return "Swanna"
	case 582:
		return "Vanillite"
	case 583:
		return "Vanillish"
	case 584:
		return "Vanilluxe"
	case 585:
		switch formIndex {
		case 0:
			return "Deerling-spring"
		case 1:
			return "Deerling-summer"
		case 2:
			return "Deerling-autumn"
		case 3:
			return "Deerling-winter"
		}
		return "Deerling"
	case 586:
		switch formIndex {
		case 0:
			return "Sawsbuck-spring"
		case 1:
			return "Sawsbuck-summer"
		case 2:
			return "Sawsbuck-autumn"
		case 3:
			return "Sawsbuck-winter"
		}
		return "Sawsbuck"
	case 587:
		return "Emolga"
	case 588:
		return "Karrablast"
	case 589:
		return "Escavalier"
	case 590:
		return "Foongus"
	case 591:
		return "Amoonguss"
	case 592:
		return "Frillish"
	case 593:
		return "Jellicent"
	case 594:
		return "Alomomola"
	case 595:
		return "Joltik"
	case 596:
		return "Galvantula"
	case 597:
		return "Ferroseed"
	case 598:
		return "Ferrothorn"
	case 599:
		return "Klink"
	case 600:
		return "Klang"
	case 601:
		return "Klinklang"
	case 602:
		return "Tynamo"
	case 603:
		return "Eelektrik"
	case 604:
		return "Eelektross"
	case 605:
		return "Elgyem"
	case 606:
		return "Beheeyem"
	case 607:
		return "Litwick"
	case 608:
		return "Lampent"
	case 609:
		return "Chandelure"
	case 610:
		return "Axew"
	case 611:
		return "Fraxure"
	case 612:
		return "Haxorus"
	case 613:
		return "Cubchoo"
	case 614:
		return "Beartic"
	case 615:
		return "Cryogonal"
	case 616:
		return "Shelmet"
	case 617:
		return "Accelgor"
	case 618:
		return "Stunfisk"
	case 619:
		return "Mienfoo"
	case 620:
		return "Mienshao"
	case 621:
		return "Druddigon"
	case 622:
		return "Golett"
	case 623:
		return "Golurk"
	case 624:
		return "Pawniard"
	case 625:
		return "Bisharp"
	case 626:
		return "Bouffalant"
	case 627:
		return "Rufflet"
	case 628:
		return "Braviary"
	case 629:
		return "Vullaby"
	case 630:
		return "Mandibuzz"
	case 631:
		return "Heatmor"
	case 632:
		return "Durant"
	case 633:
		return "Deino"
	case 634:
		return "Zweilous"
	case 635:
		return "Hydreigon"
	case 636:
		return "Larvesta"
	case 637:
		return "Volcarona"
	case 638:
		return "Cobalion"
	case 639:
		return "Terrakion"
	case 640:
		return "Virizion"
	case 641:
		switch formIndex {
		case 0:
			return "Tornadus-incarnate"
		case 1:
			return "Tornadus-therian"
		}
		return "Tornadus"
	case 642:
		switch formIndex {
		case 0:
			return "Thundurus-incarnate"
		case 1:
			return "Thundurus-therian"
		}
		return "Thundurus"
	case 643:
		return "Reshiram"
	case 644:
		return "Zekrom"
	case 645:
		switch formIndex {
		case 0:
			return "Landorus-incarnate"
		case 1:
			return "Landorus-therian"
		}
		return "Landorus"
	case 646:
		switch formIndex {
		case 0:
			return "Kyurem"
		case 1:
			return "Kyurem-black"
		case 2:
			return "Kyurem-white"
		}
		return "Kyurem"
	case 647:
		switch formIndex {
		case 0:
			return "Keldeo-ordinary"
		case 1:
			return "Keldeo-resolute"
		}
		return "Keldeo"
	case 648:
		switch formIndex {
		case 0:
			return "Meloetta-aria"
		case 1:
			return "Meloetta-pirouette"
		}
		return "Meloetta"
	case 649:
		switch formIndex {
		case 0:
			return "Genesect"
		case 1:
			return "Genesect-shock"
		case 2:
			return "Genesect-burn"
		case 3:
			return "Genesect-chill"
		case 4:
			return "Genesect-douse"
		}
		return "Genesect"
	case 650:
		return "Chespin"
	case 651:
		return "Quilladin"
	case 652:
		return "Chesnaught"
	case 653:
		return "Fennekin"
	case 654:
		return "Braixen"
	case 655:
		return "Delphox"
	case 656:
		switch formIndex {
		case 0:
			return "Froakie"
		case 1:
			return "Froakie"
		}
		return "Froakie"
	case 657:
		switch formIndex {
		case 0:
			return "Frogadier"
		case 1:
			return "Frogadier"
		}
		return "Frogadier"
	case 658:
		switch formIndex {
		case 0:
			return "Greninja"
		case 1:
			return "Greninja"
		case 2:
			return "Greninja-ash"
		}
		return "Greninja"
	case 659:
		return "Bunnelby"
	case 660:
		return "Diggersby"
	case 661:
		return "Fletchling"
	case 662:
		return "Fletchinder"
	case 663:
		return "Talonflame"
	case 664:
		switch formIndex {
		case 0:
			return "Scatterbug"
		case 1:
			return "Scatterbug"
		case 2:
			return "Scatterbug"
		case 3:
			return "Scatterbug"
		case 4:
			return "Scatterbug"
		case 5:
			return "Scatterbug"
		case 6:
			return "Scatterbug"
		case 7:
			return "Scatterbug"
		case 8:
			return "Scatterbug"
		case 9:
			return "Scatterbug"
		case 10:
			return "Scatterbug"
		case 11:
			return "Scatterbug"
		case 12:
			return "Scatterbug"
		case 13:
			return "Scatterbug"
		case 14:
			return "Scatterbug"
		case 15:
			return "Scatterbug"
		case 16:
			return "Scatterbug"
		case 17:
			return "Scatterbug"
		case 18:
			return "Scatterbug"
		case 19:
			return "Scatterbug"
		}
		return "Scatterbug"
	case 665:
		switch formIndex {
		case 0:
			return "Spewpa"
		case 1:
			return "Spewpa"
		case 2:
			return "Spewpa"
		case 3:
			return "Spewpa"
		case 4:
			return "Spewpa"
		case 5:
			return "Spewpa"
		case 6:
			return "Spewpa"
		case 7:
			return "Spewpa"
		case 8:
			return "Spewpa"
		case 9:
			return "Spewpa"
		case 10:
			return "Spewpa"
		case 11:
			return "Spewpa"
		case 12:
			return "Spewpa"
		case 13:
			return "Spewpa"
		case 14:
			return "Spewpa"
		case 15:
			return "Spewpa"
		case 16:
			return "Spewpa"
		case 17:
			return "Spewpa"
		case 18:
			return "Spewpa"
		case 19:
			return "Spewpa"
		}
		return "Spewpa"
	case 666:
		switch formIndex {
		case 0:
			return "Vivillon-meadow"
		case 1:
			return "Vivillon-icy-snow"
		case 2:
			return "Vivillon-polar"
		case 3:
			return "Vivillon-tundra"
		case 4:
			return "Vivillon-continental"
		case 5:
			return "Vivillon-garden"
		case 6:
			return "Vivillon-elegant"
		case 7:
			return "Vivillon-modern"
		case 8:
			return "Vivillon-marine"
		case 9:
			return "Vivillon-archipelago"
		case 10:
			return "Vivillon-high-plains"
		case 11:
			return "Vivillon-sandstorm"
		case 12:
			return "Vivillon-river"
		case 13:
			return "Vivillon-monsoon"
		case 14:
			return "Vivillon-savanna"
		case 15:
			return "Vivillon-sun"
		case 16:
			return "Vivillon-ocean"
		case 17:
			return "Vivillon-jungle"
		case 18:
			return "Vivillon-fancy"
		case 19:
			return "Vivillon-poke-ball"
		}
		return "Vivillon"
	case 667:
		return "Litleo"
	case 668:
		return "Pyroar"
	case 669:
		switch formIndex {
		case 0:
			return "Flabébé-red"
		case 1:
			return "Flabébé-yellow"
		case 2:
			return "Flabébé-orange"
		case 3:
			return "Flabébé-blue"
		case 4:
			return "Flabébé-white"
		}
		return "Flabébé"
	case 670:
		switch formIndex {
		case 0:
			return "Floette-red"
		case 1:
			return "Floette-yellow"
		case 2:
			return "Floette-orange"
		case 3:
			return "Floette-blue"
		case 4:
			return "Floette-white"
		}
		return "Floette"
	case 671:
		switch formIndex {
		case 0:
			return "Florges-red"
		case 1:
			return "Florges-yellow"
		case 2:
			return "Florges-orange"
		case 3:
			return "Florges-blue"
		case 4:
			return "Florges-white"
		}
		return "Florges"
	case 672:
		return "Skiddo"
	case 673:
		return "Gogoat"
	case 674:
		return "Pancham"
	case 675:
		return "Pangoro"
	case 676:
		switch formIndex {
		case 0:
			return "Furfrou"
		case 1:
			return "Furfrou-heart"
		case 2:
			return "Furfrou-star"
		case 3:
			return "Furfrou-diamond"
		case 4:
			return "Furfrou-debutante"
		case 5:
			return "Furfrou-matron"
		case 6:
			return "Furfrou-dandy"
		case 7:
			return "Furfrou-la-reine"
		case 8:
			return "Furfrou-kabuki"
		case 9:
			return "Furfrou-pharaoh"
		}
		return "Furfrou"
	case 677:
		return "Espurr"
	case 678:
		switch formIndex {
		case 0:
			return "Meowstic"
		case 1:
			return "Meowstic-female"
		}
		return "Meowstic"
	case 679:
		return "Honedge"
	case 680:
		return "Doublade"
	case 681:
		switch formIndex {
		case 0:
			return "Aegislash"
		case 1:
			return "Aegislash-blade"
		}
		return "Aegislash"
	case 682:
		return "Spritzee"
	case 683:
		return "Aromatisse"
	case 684:
		return "Swirlix"
	case 685:
		return "Slurpuff"
	case 686:
		return "Inkay"
	case 687:
		return "Malamar"
	case 688:
		return "Binacle"
	case 689:
		return "Barbaracle"
	case 690:
		return "Skrelp"
	case 691:
		return "Dragalge"
	case 692:
		return "Clauncher"
	case 693:
		return "Clawitzer"
	case 694:
		return "Helioptile"
	case 695:
		return "Heliolisk"
	case 696:
		return "Tyrunt"
	case 697:
		return "Tyrantrum"
	case 698:
		return "Amaura"
	case 699:
		return "Aurorus"
	case 700:
		return "Sylveon"
	case 701:
		return "Hawlucha"
	case 702:
		return "Dedenne"
	case 703:
		return "Carbink"
	case 704:
		return "Goomy"
	case 705:
		return "Sliggoo"
	case 706:
		return "Goodra"
	case 707:
		return "Klefki"
	case 708:
		return "Phantump"
	case 709:
		return "Trevenant"
	case 710:
		switch formIndex {
		case 0:
			return "Pumpkaboo"
		case 1:
			return "Pumpkaboo"
		case 2:
			return "Pumpkaboo"
		case 3:
			return "Pumpkaboo"
		}
		return "Pumpkaboo"
	case 711:
		switch formIndex {
		case 0:
			return "Gourgeist"
		case 1:
			return "Gourgeist"
		case 2:
			return "Gourgeist"
		case 3:
			return "Gourgeist"
		}
		return "Gourgeist"
	case 712:
		return "Bergmite"
	case 713:
		return "Avalugg"
	case 714:
		return "Noibat"
	case 715:
		return "Noivern"
	case 716:
		switch formIndex {
		case 0:
			return "Xerneas-neutral"
		case 1:
			return "Xerneas-active"
		}
		return "Xerneas"
	case 717:
		return "Yveltal"
	case 718:
		switch formIndex {
		case 0:
			return "Zygarde"
		case 1:
			return "Zygarde-10"
		case 2:
			return "Zygarde"
		case 3:
			return "Zygarde-10"
		case 4:
			return "Zygarde-complete"
		case 5:
			return "Zygarde-complete"
		}
		return "Zygarde"
	case 719:
		switch formIndex {
		case 0:
			return "Diancie"
		case 1:
			return "Diancie-mega"
		}
		return "Diancie"
	case 720:
		switch formIndex {
		case 0:
			return "Hoopa"
		case 1:
			return "Hoopa-unbound"
		}
		return "Hoopa"
	case 721:
		return "Volcanion"
	case 722:
		return "Rowlet"
	case 723:
		return "Dartrix"
	case 724:
		return "Decidueye"
	case 725:
		return "Litten"
	case 726:
		return "Torracat"
	case 727:
		return "Incineroar"
	case 728:
		return "Popplio"
	case 729:
		return "Brionne"
	case 730:
		return "Primarina"
	case 731:
		return "Pikipek"
	case 732:
		return "Trumbeak"
	case 733:
		return "Toucannon"
	case 734:
		return "Yungoos"
	case 735:
		return "Gumshoos"
	case 736:
		return "Grubbin"
	case 737:
		return "Charjabug"
	case 738:
		return "Vikavolt"
	case 739:
		return "Crabrawler"
	case 740:
		return "Crabominable"
	case 741:
		switch formIndex {
		case 0:
			return "Oricorio"
		case 1:
			return "Oricorio-pompom"
		case 2:
			return "Oricorio-pau"
		case 3:
			return "Oricorio-sensu"
		}
		return "Oricorio"
	case 742:
		return "Cutiefly"
	case 743:
		return "Ribombee"
	case 744:
		switch formIndex {
		case 0:
			return "Rockruff"
		case 1:
			return "Rockruff"
		}
		return "Rockruff"
	case 745:
		switch formIndex {
		case 0:
			return "Lycanroc"
		case 1:
			return "Lycanroc-midnight"
		case 2:
			return "Lycanroc-dusk"
		}
		return "Lycanroc"
	case 746:
		switch formIndex {
		case 0:
			return "Wishiwashi"
		case 1:
			return "Wishiwashi-school"
		}
		return "Wishiwashi"
	case 747:
		return "Mareanie"
	case 748:
		return "Toxapex"
	case 749:
		return "Mudbray"
	case 750:
		return "Mudsdale"
	case 751:
		return "Dewpider"
	case 752:
		return "Araquanid"
	case 753:
		return "Fomantis"
	case 754:
		return "Lurantis"
	case 755:
		return "Morelull"
	case 756:
		return "Shiinotic"
	case 757:
		return "Salandit"
	case 758:
		return "Salazzle"
	case 759:
		return "Stufful"
	case 760:
		return "Bewear"
	case 761:
		return "Bounsweet"
	case 762:
		return "Steenee"
	case 763:
		return "Tsareena"
	case 764:
		return "Comfey"
	case 765:
		return "Oranguru"
	case 766:
		return "Passimian"
	case 767:
		return "Wimpod"
	case 768:
		return "Golisopod"
	case 769:
		return "Sandygast"
	case 770:
		return "Palossand"
	case 771:
		return "Pyukumuku"
	case 772:
		return "Type: Null"
	case 773:
		switch formIndex {
		case 0:
			return "Silvally"
		case 1:
			return "Silvally-fighting"
		case 2:
			return "Silvally-flying"
		case 3:
			return "Silvally-poison"
		case 4:
			return "Silvally-ground"
		case 5:
			return "Silvally-rock"
		case 6:
			return "Silvally-bug"
		case 7:
			return "Silvally-ghost"
		case 8:
			return "Silvally-steel"
		case 9:
			return "Silvally-fire"
		case 10:
			return "Silvally-water"
		case 11:
			return "Silvally-grass"
		case 12:
			return "Silvally-electric"
		case 13:
			return "Silvally-psychic"
		case 14:
			return "Silvally-ice"
		case 15:
			return "Silvally-dragon"
		case 16:
			return "Silvally-dark"
		case 17:
			return "Silvally-fairy"
		}
		return "Silvally"
	case 774:
		switch formIndex {
		case 0:
			return "Minior"
		case 1:
			return "Minior"
		case 2:
			return "Minior"
		case 3:
			return "Minior"
		case 4:
			return "Minior"
		case 5:
			return "Minior"
		case 6:
			return "Minior"
		case 7:
			return "Minior-red"
		case 8:
			return "Minior-orange"
		case 9:
			return "Minior-yellow"
		case 10:
			return "Minior-green"
		case 11:
			return "Minior-blue"
		case 12:
			return "Minior-indigo"
		case 13:
			return "Minior-violet"
		}
		return "Minior"
	case 775:
		return "Komala"
	case 776:
		return "Turtonator"
	case 777:
		return "Togedemaru"
	case 778:
		switch formIndex {
		case 0:
			return "Mimikyu-disguised"
		case 1:
			return "Mimikyu-busted"
		}
		return "Mimikyu"
	case 779:
		return "Bruxish"
	case 780:
		return "Drampa"
	case 781:
		return "Dhelmise"
	case 782:
		return "Jangmo-o"
	case 783:
		return "Hakamo-o"
	case 784:
		return "Kommo-o"
	case 785:
		return "Tapu Koko"
	case 786:
		return "Tapu Lele"
	case 787:
		return "Tapu Bulu"
	case 788:
		return "Tapu Fini"
	case 789:
		return "Cosmog"
	case 790:
		return "Cosmoem"
	case 791:
		return "Solgaleo"
	case 792:
		return "Lunala"
	case 793:
		return "Nihilego"
	case 794:
		return "Buzzwole"
	case 795:
		return "Pheromosa"
	case 796:
		return "Xurkitree"
	case 797:
		return "Celesteela"
	case 798:
		return "Kartana"
	case 799:
		return "Guzzlord"
	case 800:
		switch formIndex {
		case 0:
			return "Necrozma"
		case 1:
			return "Necrozma-dusk-mane"
		case 2:
			return "Necrozma-dawn-wings"
		case 3:
			return "Necrozma-ultra"
		}
		return "Necrozma"
	case 801:
		switch formIndex {
		case 0:
			return "Magearna"
		case 1:
			return "Magearna-original"
		}
		return "Magearna"
	case 802:
		switch formIndex {
		case 0:
			return "Marshadow"
		case 1:
			return "Marshadow-zenith"
		}
		return "Marshadow"
	case 803:
		return "Poipole"
	case 804:
		return "Naganadel"
	case 805:
		return "Stakataka"
	case 806:
		return "Blacephalon"
	case 807:
		return "Zeraora"
	case 808:
		return "Meltan"
	case 809:
		switch formIndex {
		case 0:
			return "Melmetal"
		case 1:
			return "Melmetal-gigantamax"
		}
		return "Melmetal"
	case 810:
		return "Grookey"
	case 811:
		return "Thwackey"
	case 812:
		switch formIndex {
		case 0:
			return "Rillaboom"
		case 1:
			return "Rillaboom-gigantamax"
		}
		return "Rillaboom"
	case 813:
		return "Scorbunny"
	case 814:
		return "Raboot"
	case 815:
		switch formIndex {
		case 0:
			return "Cinderace"
		case 1:
			return "Cinderace-gigantamax"
		}
		return "Cinderace"
	case 816:
		return "Sobble"
	case 817:
		return "Drizzile"
	case 818:
		switch formIndex {
		case 0:
			return "Inteleon"
		case 1:
			return "Inteleon-gigantamax"
		}
		return "Inteleon"
	case 819:
		return "Skwovet"
	case 820:
		return "Greedent"
	case 821:
		return "Rookidee"
	case 822:
		return "Corvisquire"
	case 823:
		switch formIndex {
		case 0:
			return "Corviknight"
		case 1:
			return "Corviknight-gigantamax"
		}
		return "Corviknight"
	case 824:
		return "Blipbug"
	case 825:
		return "Dottler"
	case 826:
		switch formIndex {
		case 0:
			return "Orbeetle"
		case 1:
			return "Orbeetle-gigantamax"
		}
		return "Orbeetle"
	case 827:
		return "Nickit"
	case 828:
		return "Thievul"
	case 829:
		return "Gossifleur"
	case 830:
		return "Eldegoss"
	case 831:
		return "Wooloo"
	case 832:
		return "Dubwool"
	case 833:
		return "Chewtle"
	case 834:
		switch formIndex {
		case 0:
			return "Drednaw"
		case 1:
			return "Drednaw-gigantamax"
		}
		return "Drednaw"
	case 835:
		return "Yamper"
	case 836:
		return "Boltund"
	case 837:
		return "Rolycoly"
	case 838:
		return "Carkol"
	case 839:
		switch formIndex {
		case 0:
			return "Coalossal"
		case 1:
			return "Coalossal-gigantamax"
		}
		return "Coalossal"
	case 840:
		return "Applin"
	case 841:
		switch formIndex {
		case 0:
			return "Flapple"
		case 1:
			return "Flapple-gigantamax"
		}
		return "Flapple"
	case 842:
		switch formIndex {
		case 0:
			return "Appletun"
		case 1:
			return "Appletun-gigantamax"
		}
		return "Appletun"
	case 843:
		return "Silicobra"
	case 844:
		switch formIndex {
		case 0:
			return "Sandaconda"
		case 1:
			return "Sandaconda-gigantamax"
		}
		return "Sandaconda"
	case 845:
		switch formIndex {
		case 0:
			return "Cramorant"
		case 1:
			return "Cramorant-gulping"
		case 2:
			return "Cramorant-gorging"
		}
		return "Cramorant"
	case 846:
		return "Arrokuda"
	case 847:
		return "Barraskewda"
	case 848:
		return "Toxel"
	case 849:
		switch formIndex {
		case 0:
			return "Toxtricity"
		case 1:
			return "Toxtricity-lowkey"
		case 2:
			return "Toxtricity-gigantamax"
		}
		return "Toxtricity"
	case 850:
		return "Sizzlipede"
	case 851:
		switch formIndex {
		case 0:
			return "Centiskorch"
		case 1:
			return "Centiskorch-gigantamax"
		}
		return "Centiskorch"
	case 852:
		return "Clobbopus"
	case 853:
		return "Grapploct"
	case 854:
		switch formIndex {
		case 0:
			return "Sinistea"
		case 1:
			return "Sinistea"
		}
		return "Sinistea"
	case 855:
		switch formIndex {
		case 0:
			return "Polteageist"
		case 1:
			return "Polteageist"
		}
		return "Polteageist"
	case 856:
		return "Hatenna"
	case 857:
		return "Hattrem"
	case 858:
		switch formIndex {
		case 0:
			return "Hatterene"
		case 1:
			return "Hatterene-gigantamax"
		}
		return "Hatterene"
	case 859:
		return "Impidimp"
	case 860:
		return "Morgrem"
	case 861:
		switch formIndex {
		case 0:
			return "Grimmsnarl"
		case 1:
			return "Grimmsnarl-gigantamax"
		}
		return "Grimmsnarl"
	case 862:
		return "Obstagoon"
	case 863:
		return "Perrserker"
	case 864:
		return "Cursola"
	case 865:
		return "Sirfetch'd"
	case 866:
		return "Mr. Rime"
	case 867:
		return "Runerigus"
	case 868:
		return "Milcery"
	case 869:
		switch formIndex {
		case 0:
			return "Alcremie"
		case 1:
			return "Alcremie-ruby-cream"
		case 2:
			return "Alcremie-matcha-cream"
		case 3:
			return "Alcremie-mint-cream"
		case 4:
			return "Alcremie-lemon-cream"
		case 5:
			return "Alcremie-salted-cream"
		case 6:
			return "Alcremie-ruby-swirl"
		case 7:
			return "Alcremie-caramel-swirl"
		case 8:
			return "Alcremie-rainbow-swirl"
		case 9:
			return "Alcremie-gigantamax"
		}
		return "Alcremie"
	case 870:
		return "Falinks"
	case 871:
		return "Pincurchin"
	case 872:
		return "Snom"
	case 873:
		return "Frosmoth"
	case 874:
		return "Stonjourner"
	case 875:
		switch formIndex {
		case 0:
			return "Eiscue"
		case 1:
			return "Eiscue-no-ice"
		}
		return "Eiscue"
	case 876:
		switch formIndex {
		case 0:
			return "Indeedee"
		case 1:
			return "Indeedee-female"
		}
		return "Indeedee"
	case 877:
		switch formIndex {
		case 0:
			return "Morpeko"
		case 1:
			return "Morpeko-hangry"
		}
		return "Morpeko"
	case 878:
		return "Cufant"
	case 879:
		switch formIndex {
		case 0:
			return "Copperajah"
		case 1:
			return "Copperajah-gigantamax"
		}
		return "Copperajah"
	case 880:
		return "Dracozolt"
	case 881:
		return "Arctozolt"
	case 882:
		return "Dracovish"
	case 883:
		return "Arctovish"
	case 884:
		switch formIndex {
		case 0:
			return "Duraludon"
		case 1:
			return "Duraludon-gigantamax"
		}
		return "Duraludon"
	case 885:
		return "Dreepy"
	case 886:
		return "Drakloak"
	case 887:
		return "Dragapult"
	case 888:
		switch formIndex {
		case 0:
			return "Zacian"
		case 1:
			return "Zacian-crowned"
		}
		return "Zacian"
	case 889:
		switch formIndex {
		case 0:
			return "Zamazenta"
		case 1:
			return "Zamazenta-crowned"
		}
		return "Zamazenta"
	case 890:
		switch formIndex {
		case 0:
			return "Eternatus"
		case 1:
			return "Eternatus-eternamax"
		}
		return "Eternatus"
	case 891:
		return "Kubfu"
	case 892:
		switch formIndex {
		case 0:
			return "Urshifu"
		case 1:
			return "Urshifu-rapid-strike"
		case 2:
			return "Urshifu-gigantamax-single"
		case 3:
			return "Urshifu-gigantamax-rapid"
		}
		return "Urshifu"
	case 893:
		switch formIndex {
		case 0:
			return "Zarude"
		case 1:
			return "Zarude-dada"
		}
		return "Zarude"
	case 894:
		return "Regieleki"
	case 895:
		return "Regidrago"
	case 896:
		return "Glastrier"
	case 897:
		return "Spectrier"
	case 898:
		switch formIndex {
		case 0:
			return "Calyrex"
		case 1:
			return "Calyrex-ice"
		case 2:
			return "Calyrex-shadow"
		}
		return "Calyrex"
	case 899:
		return "Wyrdeer"
	case 900:
		return "Kleavor"
	case 901:
		return "Ursaluna"
	case 902:
		switch formIndex {
		case 0:
			return "Basculegion"
		case 1:
			return "Basculegion-female"
		}
		return "Basculegion"
	case 903:
		return "Sneasler"
	case 904:
		return "Overqwil"
	case 905:
		switch formIndex {
		case 0:
			return "Enamorus-incarnate"
		case 1:
			return "Enamorus-therian"
		}
		return "Enamorus"
	case 906:
		return "Sprigatito"
	case 907:
		return "Floragato"
	case 908:
		return "Meowscarada"
	case 909:
		return "Fuecoco"
	case 910:
		return "Crocalor"
	case 911:
		return "Skeledirge"
	case 912:
		return "Quaxly"
	case 913:
		return "Quaxwell"
	case 914:
		return "Quaquaval"
	case 915:
		return "Lechonk"
	case 916:
		switch formIndex {
		case 0:
			return "Oinkologne"
		case 1:
			return "Oinkologne-female"
		}
		return "Oinkologne"
	case 917:
		return "Tarountula"
	case 918:
		return "Spidops"
	case 919:
		return "Nymble"
	case 920:
		return "Lokix"
	case 921:
		return "Pawmi"
	case 922:
		return "Pawmo"
	case 923:
		return "Pawmot"
	case 924:
		return "Tandemaus"
	case 925:
		switch formIndex {
		case 0:
			return "Maushold-four"
		case 1:
			return "Maushold-three"
		}
		return "Maushold"
	case 926:
		return "Fidough"
	case 927:
		return "Dachsbun"
	case 928:
		return "Smoliv"
	case 929:
		return "Dolliv"
	case 930:
		return "Arboliva"
	case 931:
		switch formIndex {
		case 0:
			return "Squawkabilly-green-plumage"
		case 1:
			return "Squawkabilly-blue-plumage"
		case 2:
			return "Squawkabilly-yellow-plumage"
		case 3:
			return "Squawkabilly-white-plumage"
		}
		return "Squawkabilly"
	case 932:
		return "Nacli"
	case 933:
		return "Naclstack"
	case 934:
		return "Garganacl"
	case 935:
		return "Charcadet"
	case 936:
		return "Armarouge"
	case 937:
		return "Ceruledge"
	case 938:
		return "Tadbulb"
	case 939:
		return "Bellibolt"
	case 940:
		return "Wattrel"
	case 941:
		return "Kilowattrel"
	case 942:
		return "Maschiff"
	case 943:
		return "Mabosstiff"
	case 944:
		return "Shroodle"
	case 945:
		return "Grafaiai"
	case 946:
		return "Bramblin"
	case 947:
		return "Brambleghast"
	case 948:
		return "Toedscool"
	case 949:
		return "Toedscruel"
	case 950:
		return "Klawf"
	case 951:
		return "Capsakid"
	case 952:
		return "Scovillain"
	case 953:
		return "Rellor"
	case 954:
		return "Rabsca"
	case 955:
		return "Flittle"
	case 956:
		return "Espathra"
	case 957:
		return "Tinkatink"
	case 958:
		return "Tinkatuff"
	case 959:
		return "Tinkaton"
	case 960:
		return "Wiglett"
	case 961:
		return "Wugtrio"
	case 962:
		return "Bombirdier"
	case 963:
		return "Finizen"
	case 964:
		switch formIndex {
		case 0:
			return "Palafin-zero"
		case 1:
			return "Palafin-hero"
		}
		return "Palafin"
	case 965:
		return "Varoom"
	case 966:
		switch formIndex {
		case 0:
			return "Revavroom"
		case 1:
			return "Revavroom-segin-starmobile"
		case 2:
			return "Revavroom-schedar-starmobile"
		case 3:
			return "Revavroom-navi-starmobile"
		case 4:
			return "Revavroom-ruchbah-starmobile"
		case 5:
			return "Revavroom-caph-starmobile"
		}
		return "Revavroom"
	case 967:
		return "Cyclizar"
	case 968:
		return "Orthworm"
	case 969:
		return "Glimmet"
	case 970:
		return "Glimmora"
	case 971:
		return "Greavard"
	case 972:
		return "Houndstone"
	case 973:
		return "Flamigo"
	case 974:
		return "Cetoddle"
	case 975:
		return "Cetitan"
	case 976:
		return "Veluza"
	case 977:
		return "Dondozo"
	case 978:
		switch formIndex {
		case 0:
			return "Tatsugiri-curly"
		case 1:
			return "Tatsugiri-droopy"
		case 2:
			return "Tatsugiri-stretchy"
		}
		return "Tatsugiri"
	case 979:
		return "Annihilape"
	case 980:
		return "Clodsire"
	case 981:
		return "Farigiraf"
	case 982:
		switch formIndex {
		case 0:
			return "Dudunsparce"
		case 1:
			return "Dudunsparce-three-segment"
		}
		return "Dudunsparce"
	case 983:
		return "Kingambit"
	case 984:
		return "Great Tusk"
	case 985:
		return "Scream Tail"
	case 986:
		return "Brute Bonnet"
	case 987:
		return "Flutter Mane"
	case 988:
		return "Slither Wing"
	case 989:
		return "Sandy Shocks"
	case 990:
		return "Iron Treads"
	case 991:
		return "Iron Bundle"
	case 992:
		return "Iron Hands"
	case 993:
		return "Iron Jugulis"
	case 994:
		return "Iron Moth"
	case 995:
		return "Iron Thorns"
	case 996:
		return "Frigibax"
	case 997:
		return "Arctibax"
	case 998:
		return "Baxcalibur"
	case 999:
		switch formIndex {
		case 0:
			return "Gimmighoul"
		case 1:
			return "Gimmighoul-roaming"
		}
		return "Gimmighoul"
	case 1000:
		return "Gholdengo"
	case 1001:
		return "Wo-Chien"
	case 1002:
		return "Chien-Pao"
	case 1003:
		return "Ting-Lu"
	case 1004:
		return "Chi-Yu"
	case 1005:
		return "Roaring Moon"
	case 1006:
		return "Iron Valiant"
	case 1007:
		switch formIndex {
		case 0:
			return "Koraidon-apex-build"
		case 1:
			return "Koraidon-limited-build"
		case 2:
			return "Koraidon-sprinting-build"
		case 3:
			return "Koraidon-swimming-build"
		case 4:
			return "Koraidon-gliding-build"
		}
		return "Koraidon"
	case 1008:
		switch formIndex {
		case 0:
			return "Miraidon-ultimate-mode"
		case 1:
			return "Miraidon-low-power-mode"
		case 2:
			return "Miraidon-drive-mode"
		case 3:
			return "Miraidon-aquatic-mode"
		case 4:
			return "Miraidon-glide-mode"
		}
		return "Miraidon"
	case 1009:
		return "Walking Wake"
	case 1010:
		return "Iron Leaves"
	case 1011:
		return "Dipplin"
	case 1012:
		switch formIndex {
		case 0:
			return "Poltchageist-counterfeit"
		case 1:
			return "Poltchageist-artisan"
		}
		return "Poltchageist"
	case 1013:
		switch formIndex {
		case 0:
			return "Sinistcha-unremarkable"
		case 1:
			return "Sinistcha-masterpiece"
		}
		return "Sinistcha"
	case 1014:
		return "Okidogi"
	case 1015:
		return "Munkidori"
	case 1016:
		return "Fezandipiti"
	case 1017:
		switch formIndex {
		case 0:
			return "Ogerpon-teal-mask"
		case 1:
			return "Ogerpon-wellspring-mask"
		case 2:
			return "Ogerpon-hearthflame-mask"
		case 3:
			return "Ogerpon-cornerstone-mask"
		case 4:
			return "Ogerpon-teal-mask-tera"
		case 5:
			return "Ogerpon-wellspring-mask-tera"
		case 6:
			return "Ogerpon-hearthflame-mask-tera"
		case 7:
			return "Ogerpon-cornerstone-mask-tera"
		}
		return "Ogerpon"
	case 1018:
		return "Archaludon"
	case 1019:
		return "Hydrapple"
	case 1020:
		return "Gouging Fire"
	case 1021:
		return "Raging Bolt"
	case 1022:
		return "Iron Boulder"
	case 1023:
		return "Iron Crown"
	case 1024:
		switch formIndex {
		case 0:
			return "Terapagos"
		case 1:
			return "Terapagos-terastal"
		case 2:
			return "Terapagos-stellar"
		}
		return "Terapagos"
	case 1025:
		return "Pecharunt"
	case 2019:
		return "Rattata-Paldea"
	case 2020:
		return "Raticate-Paldea"
	case 2026:
		return "Raichu-Paldea"
	case 2027:
		return "Sandshrew-Paldea"
	case 2028:
		return "Sandslash-Paldea"
	case 2037:
		return "Vulpix-Paldea"
	case 2038:
		return "Ninetales-Paldea"
	case 2050:
		return "Diglett-Paldea"
	case 2051:
		return "Dugtrio-Paldea"
	case 2052:
		return "Meowth-Paldea"
	case 2053:
		return "Persian-Paldea"
	case 2074:
		return "Geodude-Paldea"
	case 2075:
		return "Graveler-Paldea"
	case 2076:
		return "Golem-Paldea"
	case 2088:
		return "Grimer-Paldea"
	case 2089:
		return "Muk-Paldea"
	case 2103:
		return "Exeggutor-Paldea"
	case 2105:
		return "Marowak-Paldea"
	case 2670:
		return "Floette-Paldea"
	case 4052:
		return "Meowth-Paldea"
	case 4077:
		return "Ponyta-Paldea"
	case 4078:
		return "Rapidash-Paldea"
	case 4079:
		return "Slowpoke-Paldea"
	case 4080:
		return "Slowbro-Paldea"
	case 4083:
		return "Farfetch'd-Paldea"
	case 4110:
		return "Weezing-Paldea"
	case 4122:
		return "Mr. Mime-Paldea"
	case 4144:
		return "Articuno-Paldea"
	case 4145:
		return "Zapdos-Paldea"
	case 4146:
		return "Moltres-Paldea"
	case 4199:
		return "Slowking-Paldea"
	case 4222:
		return "Corsola-Paldea"
	case 4263:
		return "Zigzagoon-Paldea"
	case 4264:
		return "Linoone-Paldea"
	case 4554:
		return "Darumaka-Paldea"
	case 4555:
		switch formIndex {
		case 0:
			return "Darmanitan-Paldea"
		case 1:
			return "Darmanitan-Paldea-zen"
		}
		return "Darmanitan-Paldea"
	case 4562:
		return "Yamask-Paldea"
	case 4618:
		return "Stunfisk-Paldea"
	case 6058:
		return "Growlithe-Paldea"
	case 6059:
		return "Arcanine-Paldea"
	case 6100:
		return "Voltorb-Paldea"
	case 6101:
		return "Electrode-Paldea"
	case 6157:
		return "Typhlosion-Paldea"
	case 6211:
		return "Qwilfish-Paldea"
	case 6215:
		return "Sneasel-Paldea"
	case 6503:
		return "Samurott-Paldea"
	case 6549:
		return "Lilligant-Paldea"
	case 6570:
		return "Zorua-Paldea"
	case 6571:
		return "Zoroark-Paldea"
	case 6628:
		return "Braviary-Paldea"
	case 6705:
		return "Sliggoo-Paldea"
	case 6706:
		return "Goodra-Paldea"
	case 6713:
		return "Avalugg-Paldea"
	case 6724:
		return "Decidueye-Paldea"
	case 8128:
		switch formIndex {
		case 0:
			return "Tauros-Paldea"
		case 1:
			return "Tauros-Paldea-blaze"
		case 2:
			return "Tauros-Paldea-aqua"
		}
		return "Tauros-Paldea"
	case 8194:
		return "Wooper-Paldea"
	case 8901:
		return "Ursaluna-Paldea"

	}
	return ""
}
